import type { Metadata } from "next";
import localfont from "next/font/local"
import { Inter  } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const balken = localfont(
  {
    src : [{
      path : "../../public/Balken.ttf",
      weight : "400"
    }],
    variable : "--font-balken"
  }
)

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${balken.variable} `} >
      <body className={inter.className}>{children}</body>
    </html>
  );
}
